version: '2.1'
orbs:
  maven: circleci/maven@1.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    docker:
      - image: cimg/openjdk:8.0.362
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
        
      # Use mvn clean and package as the standard maven build phase
      # - run:
      #     name: Build
      #     command: mvn clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
workflows:
  maven_test:
    jobs:
      - test