version: '2.1'
orbs:
  maven: circleci/maven@1.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browsers'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
workflows:
  maven_test:
    jobs:
      - maven/test