version: 2.1

defaults: &defaults
    docker:
      - image: cimg/openjdk:19.0.2-browsers
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-mvn-deps-{{ checksum "pom.xml" }}
      - run: mvn install -DskipTests
      - save_cache:
          key: v1-mvn-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: |
          java --version
          google-chrome --version
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: |
          java --version
          google-chrome --version
          ls /usr/local/bin
          rm -rf /usr/local/bin/chromedriver
      - browser-tools/install-browser-tools
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - run: |
          java --version
          google-chrome --version
          ls /usr/local/bin
      - restore_cache:
          key: v1-mvn-deps-{{ checksum "pom.xml" }}
      - run: sleep 5 # sleep to allow the server some time to boot
      - run: mvn test

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - tests:
          requires:
            - dependencies